import Image1 from '@/assets/properties/three-bedroom-apartmnet-union-market-noho-washington-dc-luxury.jpeg'

const recommendedData = [
    {
        id: '1',
        image: Image1,
        title: 'Luxury 3-Bedroom Apartment in Union Market, Noho, Washington DC',
        location: 'Washington DC',
        price: '$1,200,000',
        rating: 4.5,
        reviews: 120,
        area: '1,200 sqft',
        bedrooms: 3,
        bathrooms: 2,
        parking: true,
        furnished: true,
        pets: true,
        available: true,
        type: 'Apartment',
        description: 'This luxurious 3-bedroom apartment is located in the heart of Union Market, Noho, Washington DC. It offers a spacious living area, modern kitchen, and a private balcony. The apartment is fully furnished and equipped with high-end appliances. It is located in a prime location, close to shops, restaurants, and public transportation. The apartment is available for rent immediately.',
        amenities: [
            'Air conditioning',
            'Balcony',
            'Cable TV',
            'Dishwasher',
            'Dryer',
            'Fitness center',
            'Gym',
            'Heating',
        ]
    },
    {
        id: '2',
        image: Image1,
        title: 'Luxury 3-Bedroom Apartment in Union Market, Noho, Washington DC',
        location: 'Washington DC',
        price: '$1,200,000',
        rating: 4.5,
        reviews: 120,
        area: '1,200 sqft',
        bedrooms: 3,
        bathrooms: 2,
        parking: true,
        furnished: true,
        pets: true,
        available: true,
        type: 'Apartment',
        description: 'This luxurious 3-bedroom apartment is located in the heart of Union Market, Noho, Washington DC. It offers a spacious living area, modern kitchen, and a private balcony. The apartment is fully furnished and equipped with high-end appliances. It is located in a prime location, close to shops, restaurants, and public transportation. The apartment is available for rent immediately.',
        amenities: [
            'Air conditioning',
            'Balcony',
            'Cable TV',
            'Dishwasher',
            'Dryer',
            'Fitness center',
            'Gym',
        ]
    },
    {
        id: '3',
        image: Image1,
        title: 'Luxury 3-Bedroom Apartment in Union Market, Noho, Washington DC',
        location: 'Washington DC',
        price: '$1,200,000',
        rating: 4.5,
        reviews: 120,
        area: '1,200 sqft',
        bedrooms: 3,
        bathrooms: 2,
        parking: true,
        furnished: true,
        pets: true,
        available: true,
        type: 'Apartment',
        description: 'This luxurious 3-bedroom apartment is located in the heart of Union Market, Noho, Washington DC. It offers a spacious living area, modern kitchen, and a private balcony. The apartment is fully furnished and equipped with high-end appliances. It is located in a prime location, close to shops, restaurants, and public transportation. The apartment is available for rent immediately.',
        amenities: [
            'Air conditioning',
            'Balcony',
            'Cable TV',
            'Dishwasher',
            'Dryer',
        ]
    },
    {
        id: '4',
        image: Image1,
        title: 'Luxury 3-Bedroom Apartment in Union Market, Noho, Washington DC',
        location: 'Washington DC',
        price: '$1,200,000',
        rating: 4.5,
        reviews: 120,
        area: '1,200 sqft',
        bedrooms: 3,
        bathrooms: 2,
        parking: true,
        furnished: true,
        pets: true,
        available: true,
        type: 'Apartment',
        description: 'This luxurious 3-bedroom apartment is located in the heart of Union Market, Noho, Washington DC. It offers a spacious living area, modern kitchen, and a private balcony. The apartment is fully furnished and equipped with high-end appliances. It is located in a prime location, close to shops, restaurants, and public transportation. The apartment is available for rent immediately.',
        amenities: [
            'Air conditioning',
            'Balcony',
            'Cable TV',
            'Dishwasher',
            'Dryer',
        ]
    },
    {
        id: '5',
        image: Image1,
        title: 'Luxury 3-Bedroom Apartment in Union Market, Noho, Washington DC',
        location: 'Washington DC',
        price: '$1,200,000',
        rating: 4.5,
        reviews: 120,
        area: '1,200 sqft',
        bedrooms: 3,
        bathrooms: 2,
        parking: true,
        furnished: true,
        pets: true,
        available: true,
        type: 'Apartment',
        description: 'This luxurious 3-bedroom apartment is located in the heart of Union Market, Noho, Washington DC. It offers a spacious living area, modern kitchen, and a private balcony. The apartment is fully furnished and equipped with high-end appliances. It is located in a prime location, close to shops, restaurants, and public transportation. The apartment is available for rent immediately.',
        amenities: [
            'Air conditioning',
            'Balcony',
            'Cable TV',
            'Dishwasher',
            'Dryer',
        ]
    }
]


export default recommendedData